### ISSUE TITLE
Change maintainer

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/pdfjs#4]
Per https://github.com/backdrop-contrib/pdfjs/pull/2#issuecomment-1415483597

**Comment by laryn** [comment]
@opi Per your comment indicating you don't have time to work on this and are hoping for another person to maintain, I will add my name. (PR submitted). Thanks for your work on this module and Backdrop over the years!

**Comment by opi** [comment]
Thanks! I've added you as an admin for this repository
